
use C21_DB1
Go

-- Declare variable 

Declare @DepartmentID INT;
Declare @STAER_DATE DATE;
DECLARE @END_DATE DATE;
DECLARE @TOTALEMPLOYEES INT;
DECLARE @DEPARTMENTNAME NVARCHAR(50);

-- SET VALUES TO VARIABLES

SET @DepartmentID = 3;
SET @STAER_DATE = '2023-01-01';
SET @END_DATE = '2023-12-31';


SELECT @DEPARTMENTNAME = NAME FROM Departments 
WHERE DepartmentID = @DepartmentID;

SELECT @TOTALEMPLOYEES = COUNT(Employees.EmployeeID) FROM Employees
WHERE DepartmentID = @DepartmentID
AND HireDate BETWEEN @STAER_DATE AND @END_DATE;


-- print results on console

PRINT 'DATA OF EMPLOYEES WORK AT DEPALRTMENT => ' + @DEPARTMENTNAME;
PRINT 'TOTAL EMPLOYEES WORK AT THERE "' + CAST (@TOTALEMPLOYEES as varchar)+' " EMPLOYEES';
PRINT ' DATES => FROM : ' + CAST(YEAR(@STAER_DATE)as VARCHAR) + ' TO : ' + CAST(YEAR(@END_DATE) as VARCHAR);


